### PR TITLE
Don't clear whole line every time; instead, clear everything after end of line

### PR DESCRIPTION
**Pull request by myndzi**
This makes the progress bar much less flickery on laggy or bursty connections over SSH, etc.

### CODE REVIEW

**Comment by jdan** [comment]
How does this work? Won't it clear whatever it just drew?

**Comment by myndzi** [comment]
Previously, when drawing an updated line, the code did this:

- clear the whole line
- go to the start of the line
- print the new line

Now, when drawing an updated line, the code does this:

- go to the start of the line
- print the new line
- clear the line from here to the end

**Comment by hallas** [comment]
From what I read it looks like it writes something, then clears the line from the point where the cursor is, clearing everything in between.

So your solution writes a new line on the old one and clears anything that might have been left over by the old write?

**Comment by myndzi** [comment]
Yes. Not sure what you mean by "in between" - note that the first step is "go to the beginning of the line"

**Comment by jdan** [comment]
Yep, way better. LGTM - thank you!

**Comment by hallas** [comment]
Nice change. Thanks.

**Pull request merged**
