### PR TITLE
Adding an optional label

### PR DESCRIPTION
**Pull request by ricardomccerqueira**
Loading about 3000 images on a project I have, used this preloader, and something that I found useful, was to be able to view which image group is currently loading.
Submitted the pull request just in case someone else may find this useful.

Preview:
[          ] 1% eta: 117.0s   downloading 41/3970   imageX

### CODE REVIEW

**Comment by gaborcsardi** [comment]
@ricardomccerqueira I guess this is already possible with custom tokens.

**Comment by jrouleau** [comment]
Code change not required. Can be easily done with the (undocumented) custom tokens feature.

```javascript
var list = [
  'image01.jpg', 'image02.jpg', 'image03.jpg', 'image04.jpg', 'image05.jpg',
  'image06.jpg', 'image07.jpg', 'image08.jpg', 'image09.jpg', 'image10.jpg'
]

var bar = new ProgressBar(':percent eta: :eta downloading :current/:total :file', {
  total: list.length,
})

var id = setInterval(function (){
  bar.tick({
    'file': list[bar.curr]
  })
  if (bar.complete) {
    clearInterval(id)
  }
}, 500)
```

**Comment by jdan** [comment]
Yeah, better to just pass some options to `tick` - we should add this to the README. Thanks anyway though!

**Comment by jrouleau** [comment]
I'm adding documentation and an example. I should have a PR up shortly.

**Pull request closed without merging**
